#!/bin/sh
JQA()
{
    [ $# -lt 2 ] && echo "JQA (jq-Apply)" && echo "Usage: JQA <filename> <jq filter> [jq arg[,jq arg]...]" && exit 1
    [ ! -f "${1}" ] && echo "${1} is not a file" && exit 1
    cat "${1}" | jq --indent 1 "${2}" ${3-} > "${1}".tmp && mv "${1}".tmp "${1}"
}

