#!/bin/sh
. "$(dirname "${0}")"/../JQ # include JQ helper scripts
JQA "${1}" '.versionDetail."services/radiusServer"=2'

# delete freeradius config files generated by a newer config
rm -rf /etc/freeradius/3.0/uus-*
rm -rf /etc/freeradius/3.0/policy.d/uus-*
rm -rf /etc/freeradius/3.0/mods-enabled/uus-*

# delete policy groups of not supported types
# delete user'<FILTERED> policy group names for deleted policy groups
JQA "${1}" '
    (. | select(has("services")) | .services | select(has("radiusServer")) | .radiusServer) |= (
        del(.policyGroups[]? | select( .type != "filter" or .matchRule != "accept" )) |
        del(.policyGroups[]? | .type) |
        del(.policyGroups[]? | .matchRule) |
        [.policyGroups[]?.name] as $pg |
        ( .user<FILTERED>[]? |= del(.policyGroupNames[]? | . as $x | select( $pg | index($x) == null ) ) )
    )
'

exit 0
