#!/bin/sh
. "$(dirname "${0}")"/../JQ # include JQ helper scripts
JQA "${1}" '.versionDetail."services/radiusServer"=3'

# delete freeradius config files generated by a newer config
rm -rf /etc/freeradius/3.0/policy.d/uus-policy-strict-filter-id*

# delete unused attributes
JQA "${1}" '
    (. | select(has("services")) | .services | select(has("radiusServer")) | .radiusServer) |= (
        del(.strictPolicyGroups)
    )
'

exit 0
