#!/bin/bash
# backup-pihole.sh
# Backup Pi-hole/Raspberrypi configuration to MacBook, then to external BTRFS drive
# Run from MacBook Air
# Usage: ./backup-pihole.sh [backup-location]

set -e  # Exit on error

# Configuration
PIHOLE_HOST="pihole"
BACKUP_DATE=$(date +%Y%m%d-%H%M%S)
TEMP_BACKUP_DIR="$HOME/Downloads/pihole-backups"
BACKUP_NAME="pihole-backup-${BACKUP_DATE}"
BACKUP_PATH="${TEMP_BACKUP_DIR}/${BACKUP_NAME}"

# External drive path (override with argument)
EXTERNAL_DRIVE="${1:-/Volumes/BackupDrive}"
FINAL_BACKUP_PATH="${EXTERNAL_DRIVE}/homelab-backups/pihole"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=========================================="
echo "Pi-hole Backup Script"
echo "=========================================="
echo ""

# Create temp backup directory
mkdir -p "${BACKUP_PATH}"
echo -e "${GREEN}✓${NC} Created backup directory: ${BACKUP_PATH}"

# Function to backup via SSH
backup_file() {
    local source=$1
    local dest=$2
    local desc=$3

    echo -n "Backing up ${desc}... "
    if ssh -i ~/.ssh/id_ed25519_yk5cnfc "${PIHOLE_HOST}" "sudo tar czf - ${source}" > "${dest}"; then
        echo -e "${GREEN}✓${NC}"
    else
        echo -e "${RED}✗${NC}"
        return 1
    fi
}

# Function to backup via rsync (for directories)
backup_dir() {
    local source=$1
    local dest=$2
    local desc=$3

    echo -n "Backing up ${desc}... "
    mkdir -p "${dest}"
    if rsync -az --rsync-path="sudo rsync" -e "ssh -i ~/.ssh/id_ed25519_yk5cnfc" \
        "${PIHOLE_HOST}:${source}/" "${dest}/"; then
        echo -e "${GREEN}✓${NC}"
    else
        echo -e "${RED}✗${NC}"
        return 1
    fi
}

echo ""
echo "=== Phase 1: Backing up to MacBook ==="
echo ""

# Backup Pi-hole configuration directory
backup_dir "/etc/pihole" "${BACKUP_PATH}/etc-pihole" "Pi-hole config directory"

# Backup dnsmasq configuration
backup_dir "/etc/dnsmasq.d" "${BACKUP_PATH}/etc-dnsmasq.d" "dnsmasq config"

# Backup SSH configuration
echo -n "Backing up SSH config... "
ssh -i ~/.ssh/id_ed25519_yk5cnfc "${PIHOLE_HOST}" \
    "sudo tar czf - /etc/ssh/sshd_config /etc/ssh/sshd_config.backup* /etc/ssh/sshd_config.original" \
    > "${BACKUP_PATH}/ssh-config.tar.gz" 2>/dev/null || true
echo -e "${GREEN}✓${NC}"

# Backup authorized_keys
echo -n "Backing up SSH authorized_keys... "
ssh -i ~/.ssh/id_ed25519_yk5cnfc "${PIHOLE_HOST}" \
    "cat ~/.ssh/authorized_keys" > "${BACKUP_PATH}/authorized_keys" 2>/dev/null || true
echo -e "${GREEN}✓${NC}"

# Backup /etc/hosts
echo -n "Backing up /etc/hosts... "
ssh -i ~/.ssh/id_ed25519_yk5cnfc "${PIHOLE_HOST}" \
    "sudo cat /etc/hosts" > "${BACKUP_PATH}/hosts" 2>/dev/null || true
echo -e "${GREEN}✓${NC}"

# Backup network configuration
echo -n "Backing up network config... "
ssh -i ~/.ssh/id_ed25519_yk5cnfc "${PIHOLE_HOST}" \
    "sudo tar czf - /etc/network /etc/dhcpcd.conf 2>/dev/null" \
    > "${BACKUP_PATH}/network-config.tar.gz" 2>/dev/null || true
echo -e "${GREEN}✓${NC}"

# Get installed packages list
echo -n "Backing up installed packages list... "
ssh -i ~/.ssh/id_ed25519_yk5cnfc "${PIHOLE_HOST}" \
    "dpkg --get-selections" > "${BACKUP_PATH}/installed-packages.txt" 2>/dev/null || true
echo -e "${GREEN}✓${NC}"

# Get Pi-hole version info
echo -n "Backing up Pi-hole version info... "
ssh -i ~/.ssh/id_ed25519_yk5cnfc "${PIHOLE_HOST}" \
    "pihole -v" > "${BACKUP_PATH}/pihole-version.txt" 2>/dev/null || true
echo -e "${GREEN}✓${NC}"

# Get system info
echo -n "Backing up system info... "
ssh -i ~/.ssh/id_ed25519_yk5cnfc "${PIHOLE_HOST}" \
    "cat /etc/os-release && uname -a" > "${BACKUP_PATH}/system-info.txt" 2>/dev/null || true
echo -e "${GREEN}✓${NC}"

# Create backup manifest
cat > "${BACKUP_PATH}/BACKUP_MANIFEST.txt" << EOF
Pi-hole Backup Manifest
=======================
Backup Date: ${BACKUP_DATE}
Backup Location: ${BACKUP_PATH}
Source Host: ${PIHOLE_HOST}

Contents:
- etc-pihole/          Pi-hole configuration directory
- etc-dnsmasq.d/       dnsmasq configuration
- ssh-config.tar.gz    SSH server configuration (hardened)
- authorized_keys      SSH public keys
- hosts                /etc/hosts file
- network-config.tar.gz Network configuration
- installed-packages.txt List of installed packages
- pihole-version.txt   Pi-hole version information
- system-info.txt      OS and system information
- BACKUP_MANIFEST.txt  This file
- RESTORE_NOTES.txt    Restoration instructions

Generated by: backup-pihole.sh
EOF

# Create restore notes
cat > "${BACKUP_PATH}/RESTORE_NOTES.txt" << 'EOF'
Pi-hole Restoration Guide
==========================

PREREQUISITES:
1. Fresh Raspberry Pi OS (Debian) installation
2. Static IP configured (same as original: 192.168.1.69)
3. SSH enabled and accessible from MacBook
4. User 'patriark' created with sudo access

RESTORATION STEPS:

Step 1: Install Pi-hole
-----------------------
ssh patriark@192.168.1.69
curl -sSL https://install.pi-hole.net | bash
# Follow interactive installer, note web interface password

Step 2: Restore Pi-hole Configuration
-------------------------------------
# From MacBook, transfer backup
scp -r /path/to/backup/etc-pihole/* patriark@192.168.1.69:/tmp/pihole-restore/

# On Pi-hole
ssh patriark@192.168.1.69
sudo systemctl stop pihole-FTL
sudo cp -r /tmp/pihole-restore/* /etc/pihole/
sudo chown -R pihole:pihole /etc/pihole
sudo chmod 664 /etc/pihole/*.list
sudo chmod 664 /etc/pihole/gravity.db
sudo systemctl start pihole-FTL

Step 3: Restore dnsmasq Configuration
-------------------------------------
# From MacBook
scp -r /path/to/backup/etc-dnsmasq.d/* patriark@192.168.1.69:/tmp/dnsmasq-restore/

# On Pi-hole
ssh patriark@192.168.1.69
sudo cp /tmp/dnsmasq-restore/* /etc/dnsmasq.d/
sudo chown root:root /etc/dnsmasq.d/*

Step 4: Restore SSH Configuration
---------------------------------
# From MacBook
scp /path/to/backup/ssh-config.tar.gz patriark@192.168.1.69:/tmp/

# On Pi-hole
ssh patriark@192.168.1.69
cd /tmp
tar xzf ssh-config.tar.gz
sudo cp etc/ssh/sshd_config /etc/ssh/sshd_config
sudo chmod 600 /etc/ssh/sshd_config
sudo systemctl restart ssh

Step 5: Restore SSH Authorized Keys
-----------------------------------
# From MacBook
scp /path/to/backup/authorized_keys patriark@192.168.1.69:/tmp/

# On Pi-hole
ssh patriark@192.168.1.69
mkdir -p ~/.ssh
cp /tmp/authorized_keys ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
chmod 700 ~/.ssh

Step 6: Restore /etc/hosts
--------------------------
# From MacBook
scp /path/to/backup/hosts patriark@192.168.1.69:/tmp/

# On Pi-hole
ssh patriark@192.168.1.69
sudo cp /tmp/hosts /etc/hosts

Step 7: Update Gravity Database
-------------------------------
ssh patriark@192.168.1.69
pihole -g

Step 8: Verify Pi-hole Functionality
------------------------------------
# Check Pi-hole status
pihole status

# Check DNS resolution
dig @127.0.0.1 google.com

# Access web interface
# http://192.168.1.69/admin

Step 9: Test SSH with YubiKey
-----------------------------
# From MacBook
ssh -i ~/.ssh/id_ed25519_yk5cnfc pihole hostname
# Should require YubiKey touch and return "raspberrypi"

Step 10: Deploy fedora-jern Keys (if needed)
--------------------------------------------
# From MacBook
cat ~/Downloads/fedora-jern-keys/fedora-jern-*.pub | ssh pihole 'cat >> ~/.ssh/authorized_keys'

# Verify from fedora-jern
ssh jern
ssh pihole hostname  # Should work with YubiKey touch

VERIFICATION CHECKLIST:
[ ] Pi-hole web interface accessible
[ ] DNS resolution working
[ ] Blocklists updated
[ ] Custom DNS entries working (/etc/hosts)
[ ] SSH accessible from MacBook with YubiKey
[ ] SSH accessible from fedora-jern with YubiKey
[ ] Password authentication disabled
[ ] Root login disabled

NOTES:
- Pi-hole admin password will be reset during fresh install
- Reset password: pihole -a -p
- Custom blocklists preserved in adlists.list
- Local DNS entries preserved in custom.list
- Gravity database (gravity.db) contains all blocking data
EOF

echo -e "${GREEN}✓${NC} Backup manifest and restore notes created"

# Calculate backup size
BACKUP_SIZE=$(du -sh "${BACKUP_PATH}" | cut -f1)
echo ""
echo "=== Backup Summary ==="
echo "Location: ${BACKUP_PATH}"
echo "Size: ${BACKUP_SIZE}"
echo ""

# Compress entire backup
echo -n "Compressing backup... "
cd "${TEMP_BACKUP_DIR}"
tar czf "${BACKUP_NAME}.tar.gz" "${BACKUP_NAME}"
COMPRESSED_SIZE=$(du -sh "${BACKUP_NAME}.tar.gz" | cut -f1)
echo -e "${GREEN}✓${NC} (${COMPRESSED_SIZE})"
echo ""

# Check if external drive is mounted
if [ -d "${EXTERNAL_DRIVE}" ]; then
    echo "=== Phase 2: Copying to External Drive ==="
    echo ""

    # Create directory on external drive
    mkdir -p "${FINAL_BACKUP_PATH}"

    echo -n "Copying compressed backup to external drive... "
    if cp "${BACKUP_NAME}.tar.gz" "${FINAL_BACKUP_PATH}/"; then
        echo -e "${GREEN}✓${NC}"

        # Also copy uncompressed for easy access
        echo -n "Copying uncompressed backup for easy access... "
        if cp -r "${BACKUP_NAME}" "${FINAL_BACKUP_PATH}/"; then
            echo -e "${GREEN}✓${NC}"
        fi

        # Create a 'latest' symlink
        cd "${FINAL_BACKUP_PATH}"
        rm -f latest
        ln -s "${BACKUP_NAME}" latest
        echo -e "${GREEN}✓${NC} Created 'latest' symlink"

        echo ""
        echo -e "${GREEN}=== Backup Complete! ===${NC}"
        echo ""
        echo "Backup saved to:"
        echo "  1. MacBook: ${BACKUP_PATH}"
        echo "  2. MacBook (compressed): ${TEMP_BACKUP_DIR}/${BACKUP_NAME}.tar.gz"
        echo "  3. External Drive: ${FINAL_BACKUP_PATH}/${BACKUP_NAME}"
        echo "  4. External Drive (compressed): ${FINAL_BACKUP_PATH}/${BACKUP_NAME}.tar.gz"
        echo "  5. External Drive (latest): ${FINAL_BACKUP_PATH}/latest -> ${BACKUP_NAME}"
        echo ""
        echo "To restore, see: ${FINAL_BACKUP_PATH}/latest/RESTORE_NOTES.txt"
    else
        echo -e "${RED}✗${NC}"
        echo ""
        echo -e "${YELLOW}Warning: Could not copy to external drive${NC}"
        echo "Backup available on MacBook at: ${BACKUP_PATH}"
    fi
else
    echo ""
    echo -e "${YELLOW}=== External Drive Not Mounted ===${NC}"
    echo ""
    echo "Backup saved to MacBook at:"
    echo "  1. Uncompressed: ${BACKUP_PATH}"
    echo "  2. Compressed: ${TEMP_BACKUP_DIR}/${BACKUP_NAME}.tar.gz"
    echo ""
    echo "To copy to external drive manually:"
    echo "  1. Mount your BTRFS backup drive"
    echo "  2. Run: cp -r ${BACKUP_PATH} /Volumes/YourDrive/homelab-backups/pihole/"
    echo "  3. Or run: cp ${TEMP_BACKUP_DIR}/${BACKUP_NAME}.tar.gz /Volumes/YourDrive/homelab-backups/pihole/"
fi

echo ""
echo "=========================================="
