#!/bin/bash
# egress-baseline.sh — ADR-030 P7 (Tier 4) baseline survey → proposed allow-list.
#
# Run ONCE after the shadow baseline window (≥7 days). Reads the durable observatory
# state (data/egress/destinations.tsv) built by detect-egress-anomaly.sh --shadow, and:
#   1. groups each classify-service's public destinations by owner (one-time whois — at
#      BASELINE time only, never on the detector hot path),
#   2. emits a PROPOSED config/supply-chain/egress-baseline.proposed.yaml (frozen prefixes)
#      for human review + merge into egress-baseline.yaml (the deliberate checkpoint, P1),
#   3. lists ZERO-EGRESS candidates — egress-tier services with no public destination over
#      the window (blast-radius reduction; report only, never an automated network change).
#
# Output: prints a survey report to stdout; with --write, also writes the .proposed.yaml.
# Exit: 0 ok, 2 missing input.
set -uo pipefail

REPO_ROOT="${REPO_ROOT:-$HOME/containers}"
QUADLET_DIR="${QUADLET_DIR:-$REPO_ROOT/quadlets}"
EGRESS_DIR="${EGRESS_DIR:-$REPO_ROOT/data/egress}"
DEST_FILE="$EGRESS_DIR/destinations.tsv"
BASELINE_YAML="${BASELINE_YAML:-$REPO_ROOT/config/supply-chain/egress-baseline.yaml}"
PROPOSED="${PROPOSED:-$REPO_ROOT/config/supply-chain/egress-baseline.proposed.yaml}"

write=0
[ "${1:-}" = "--write" ] && write=1

[ -f "$DEST_FILE" ] || { echo "egress-baseline: no observations yet ($DEST_FILE). Run the collector/detector first." >&2; exit 2; }

is_egress() { grep -qE '^Network=systemd-reverse_proxy' "$1"; }
egress_services() {
    local f
    for f in "$QUADLET_DIR"/*.container; do
        [ -e "$f" ] || continue
        is_egress "$f" && basename "$f" .container
    done
}
EGRESS_LIST="$(egress_services | sort | paste -sd, -)"

python3 - "$DEST_FILE" "$BASELINE_YAML" "$PROPOSED" "$write" "$EGRESS_LIST" <<'PY'
import sys, ipaddress, subprocess, re, time
destp, yamlp, proposed, write_s, egress_csv = sys.argv[1:6]
write = write_s == "1"
egress_all = [s for s in egress_csv.split(",") if s]

try:
    import yaml
    cfg = yaml.safe_load(open(yamlp)) or {}
except Exception:
    cfg = {}
peer_swarm = set(cfg.get("peer_swarm_services") or [])

# service -> set of public ips  (from durable state; ports collapsed for prefix grouping)
svc_ips = {}
seen_svcs = set()
for line in open(destp):
    f = line.rstrip("\n").split("\t")
    if len(f) < 6: continue
    svc, ip = f[0], f[1]
    seen_svcs.add(svc)
    if svc in peer_swarm: continue
    svc_ips.setdefault(svc, set()).add(ip)

def whois_owner_cidr(ip):
    """Best-effort: (owner, cidr). Frozen prefix from whois; human reviews the result."""
    try:
        out = subprocess.run(["whois", ip], capture_output=True, text=True, timeout=10).stdout
    except Exception:
        return ("UNKNOWN", f"{ip}/32")
    owner = ""
    for key in ("OrgName", "org-name", "owner", "netname", "descr", "Organization"):
        m = re.search(rf"(?im)^{key}:\s*(.+)$", out)
        if m: owner = m.group(1).strip(); break
    cidr = ""
    m = re.search(r"(?im)^CIDR:\s*([0-9./, ]+)$", out) or re.search(r"(?im)^route6?:\s*([0-9a-f:./]+)$", out)
    if m:
        cidr = m.group(1).split(",")[0].strip()
    else:
        m = re.search(r"(?im)^(?:inetnum|NetRange):\s*([0-9.]+)\s*-\s*([0-9.]+)\s*$", out)
        if m:
            try:
                nets = list(ipaddress.summarize_address_range(
                    ipaddress.IPv4Address(m.group(1)), ipaddress.IPv4Address(m.group(2))))
                cidr = str(nets[0]) if nets else ""
            except Exception:
                cidr = ""
    if not cidr:
        try: cidr = str(ipaddress.ip_network(ip + "/24", strict=False))
        except ValueError: cidr = ip + "/32"
    return (owner or "UNKNOWN", cidr)

# build proposal: service -> owner -> set(cidr) (+ the ips behind each, for the note)
proposal = {}
cache = {}
for svc in sorted(svc_ips):
    for ip in sorted(svc_ips[svc]):
        if ip not in cache:
            cache[ip] = whois_owner_cidr(ip); time.sleep(0.3)
        owner, cidr = cache[ip]
        proposal.setdefault(svc, {}).setdefault(owner, {"cidrs": set(), "ips": set()})
        proposal[svc][owner]["cidrs"].add(cidr)
        proposal[svc][owner]["ips"].add(ip)

# render proposed yaml
out = []
out.append("# egress-baseline.proposed.yaml — generated by scripts/egress-baseline.sh")
out.append(f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}")
out.append("# REVIEW before merging into egress-baseline.yaml: confirm owners, widen/narrow")
out.append("# CIDRs (a provider may use several ranges), and promote shared infra to the")
out.append("# top-level `infrastructure:` block. whois-derived prefixes are best-effort.")
out.append("")
out.append("peer_swarm_services:")
for s in sorted(peer_swarm):
    out.append(f"  - {s}")
out.append("")
out.append("infrastructure: []   # promote shared destinations here after review")
out.append("")
out.append("services:")
if not proposal:
    out.append("  {}")
for svc in sorted(proposal):
    out.append(f"  {svc}:")
    for owner in sorted(proposal[svc]):
        cidrs = sorted(proposal[svc][owner]["cidrs"])
        ips = sorted(proposal[svc][owner]["ips"])
        out.append(f"    - owner: {owner}")
        out.append(f"      cidrs: [{', '.join(cidrs)}]")
        out.append(f"      note: observed {', '.join(ips[:6])}{' …' if len(ips) > 6 else ''}")
proposed_text = "\n".join(out) + "\n"

if write:
    open(proposed, "w").write(proposed_text)

# survey report
print("=" * 70)
print("ADR-030 Tier 4 — Egress Baseline Survey")
print("=" * 70)
print(f"Observed services (any public dest): {', '.join(sorted(seen_svcs)) or '(none)'}")
print(f"Peer-swarm (count-only): {', '.join(sorted(peer_swarm)) or '(none)'}")
print()
print("Classifiable destinations per service:")
for svc in sorted(svc_ips):
    print(f"  {svc}: {len(svc_ips[svc])} distinct public IP(s)")
print()
zero = sorted(set(egress_all) - seen_svcs - peer_swarm)
print("ZERO-EGRESS candidates (no public dest in window → Internal=true candidates,")
print("REPORT ONLY — manual per-service review; Feb-2026 outage precedent):")
print(f"  {', '.join(zero) or '(none)'}")
print()
if write:
    print(f"Proposed allow-list written: {proposed}")
    print("Review, merge the relevant entries into egress-baseline.yaml, then arm.")
else:
    print("--- proposed allow-list (preview; re-run with --write to save) ---")
    print(proposed_text)
PY
