#!/bin/bash
# generate-image-pin-index.sh — ADR-030 audit index (the "audit view").
#
# Parses every quadlet's Image= line and emits one reviewable document mapping
# service → repo → pinned digest → tag → mutability → egress-tier → auto-update.
# Centralises the audit view without a central write path (digests stay in the
# quadlets where Podman reads them). See ADR-030 "Architecture: where digests live".
set -euo pipefail

QUADLET_DIR="${QUADLET_DIR:-$HOME/containers/quadlets}"
OUTPUT_FILE="${OUTPUT_FILE:-$HOME/containers/docs/AUTO-IMAGE-PIN-INDEX.md}"

is_egress() { grep -qE '^Network=systemd-reverse_proxy' "$1"; }

rows=""
pinned=0; floating=0; local_builds=0; egress_floating=0; egress_auto=0; total=0

for f in "$QUADLET_DIR"/*.container; do
    name="$(basename "$f" .container)"
    img="$(grep -m1 -E '^Image=' "$f" | sed 's/^Image=//' | tr -d '[:space:]')"
    [ -n "$img" ] || continue
    total=$((total+1))

    egress="no"; is_egress "$f" && egress="yes"
    auto="no"; grep -qE '^AutoUpdate=registry' "$f" && auto="yes"
    grep -qE '^Pull=newer' "$f" && auto="yes(+Pull)"

    if [[ "$img" == localhost/* ]]; then
        repo="${img%:*}"; digest="—"; tag="${img##*:}"; status="🔨 local-build"
        local_builds=$((local_builds+1))
    elif [[ "$img" == *@sha256:* ]]; then
        repo="${img%@*}"; digest="${img##*@}"; status="🔒 pinned"
        # tag preserved in the ADR-030 comment immediately above the Image line
        tag="$(grep -m1 -oE 'tag: [^,]+' "$f" | sed 's/tag: //' || true)"
        [ -n "$tag" ] || tag="?"
        pinned=$((pinned+1))
    else
        repo="${img%:*}"; tag="${img##*:}"; digest="—"; status="⚠️ FLOATING"
        floating=$((floating+1))
        [ "$egress" = yes ] && egress_floating=$((egress_floating+1))
    fi

    [ "$auto" != "no" ] && [ "$egress" = yes ] && egress_auto=$((egress_auto+1))

    short_digest="$digest"
    [ "$digest" != "—" ] && short_digest="${digest:0:19}…"
    rows+="| ${name} | ${egress} | ${status} | \`${repo}\` | ${tag} | \`${short_digest}\` | ${auto} |"$'\n'
done

{
    echo "# Container Image Pin Index (Auto-Generated)"
    echo ""
    echo "**Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "**Source:** \`${QUADLET_DIR}\` — ADR-030 (Container Supply-Chain Trust Model)"
    echo ""
    echo "Pins live in each quadlet's \`Image=\` line (where Podman reads them); this is"
    echo "the aggregated audit view. \`tag\` is the discovery handle; the digest is the"
    echo "execution contract. Update = resolve a new digest, bake, edit the quadlet, restart."
    echo ""
    echo "## Summary"
    echo ""
    echo "| Metric | Count |"
    echo "|--------|-------|"
    echo "| Total images | ${total} |"
    echo "| 🔒 Digest-pinned | ${pinned} |"
    echo "| ⚠️ Floating (mutable tag) | ${floating} |"
    echo "| 🔨 Local builds (Tier 2) | ${local_builds} |"
    echo "| Egress-tier still floating | ${egress_floating} |"
    echo "| Egress-tier still auto-updating | ${egress_auto} |"
    echo ""
    if [ "$egress_floating" -eq 0 ] && [ "$egress_auto" -eq 0 ]; then
        echo "> ✅ **Egress invariant holds:** no reverse_proxy-tier service is floating or auto-updating."
    else
        echo "> ❌ **Egress invariant VIOLATED** — see \`scripts/audit-egress-updates.sh\`."
    fi
    echo ""
    echo "## Images"
    echo ""
    echo "| Service | Egress | Status | Repository | Tag | Digest | Auto |"
    echo "|---------|--------|--------|------------|-----|--------|------|"
    printf "%s" "$rows" | sort
    echo ""
    echo "---"
    echo ""
    echo "*Auto-generated by \`scripts/generate-image-pin-index.sh\`. Egress-tier =="
    echo "reverse_proxy network member (ADR-030 P4). Local builds (\`localhost/*\`) are"
    echo "pinned via build inputs under Tier 2, not by registry digest.*"
} > "$OUTPUT_FILE"

echo "✓ Image pin index generated: $OUTPUT_FILE"
echo "  pinned=$pinned floating=$floating local=$local_builds egress_floating=$egress_floating egress_auto=$egress_auto"
