#!/bin/bash
# Simple Service Catalog Generator
# Quick and reliable service inventory generation

set -euo pipefail

OUTPUT_FILE="${HOME}/containers/docs/AUTO-SERVICE-CATALOG.md"

# Generate catalog
{
    echo "# Service Catalog (Auto-Generated)"
    echo ""
    echo "**Generated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "**System:** $(hostname)"
    echo ""
    echo "---"
    echo ""
    echo "## Running Services"
    echo ""
    echo "| Service | Image | Status | Networks |"
    echo "|---------|-------|--------|----------|"

    # Get running containers
    podman ps --format "{{.Names}}|{{.Image}}|{{.Status}}|{{.Networks}}" | while IFS='|' read -r name image status networks; do
        # Clean up image name
        short_image=$(echo "$image" | sed 's|docker.io/library/||' | sed 's|docker.io/||' | sed 's|ghcr.io/||' | cut -c1-40)

        # Clean up networks
        clean_networks=$(echo "$networks" | sed 's/systemd-//g')

        # Determine status icon
        if echo "$status" | grep -q "Up"; then
            status_icon="✅ Up"
        else
            status_icon="❌ Down"
        fi

        echo "| $name | $short_image | $status_icon | $clean_networks |"
    done

    echo ""
    echo "---"
    echo ""
    echo "## Statistics"
    echo ""
    echo "- **Total Running:** $(podman ps | tail -n +2 | wc -l)"
    echo "- **Total Defined:** $(podman ps -a | tail -n +2 | wc -l)"
    echo "- **System Load:** $(uptime | awk -F'load average:' '{print $2}')"
    echo ""
    echo "---"
    echo ""
    echo "## Quick Links"
    echo ""
    echo "- [Homelab Architecture](20-operations/guides/homelab-architecture.md)"
    echo "- [Network Topology](AUTO-NETWORK-TOPOLOGY.md) (when generated)"
    echo "- [Dependency Graph](AUTO-DEPENDENCY-GRAPH.md) (when generated)"
    echo ""
    echo "---"
    echo ""
    echo "*Auto-generated by \`scripts/generate-service-catalog-simple.sh\`*"
} > "$OUTPUT_FILE"

echo "✓ Service catalog generated: $OUTPUT_FILE"
